### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by ifernapa10** [NestorTejero/ES2016B#100]
Existència d'una estructura de tooltips, és a dir:
Un objecte que permeti mostrar un text corresponent al tooltip.
Un script que controli els tooltips que s'han de mostrar.

**Comment by NestorTejero** [comment]
A quin milestone pertany? D'acord, veig que apareix com a "Done in Sprint 2- Team C". Afegiu el milestone a tots els issues la propera vegada!
