### ISSUE TITLE
Create loading screen, and show small history.

### ISSUE THREAD

**Issue by ifernapa10** [NestorTejero/ES2016B#102]

**Comment by Solero93** [comment]
This could be passed to the next Sprint, it's not really urgent. It's more important to fix the HUD I'd say.

**Comment by Solero93** [comment]
Don't close the issue, until it's merged into dev. I couldn't review the changes because of all the .mat files

**Comment by ire925** [comment]
when I can close your advised me

**Comment by Solero93** [comment]
I've fixed all the conflicts you and @ifernapa10 inserted (because he accepted the PR without even looking at the files that were changed.... all the 80 freaking .mat files that I had to fix xD)
