### ISSUE TITLE
Janitor - 6h

### ISSUE THREAD

**Issue by stefanlonn** [NestorTejero/ES2016B#110]
## Definitions of done:
1. Design of damage. (See character properly damaged)
2. Scaling, adapted size of models with scene.
3. Animations of walk,
   - Have to move correctly arms.
   - Have to move correctly legs.
4. Animations of attack 
   1. If character is melee:
      - Moving gun according to the arm.
   2. If character is rank:
      - Animation has to see like character is throwing an object.
5. Animation of die.
   - Have to stay on the ground before falling.
6. Integrated correctly in unity.

**Comment by NestorTejero** [comment]
No trobo la pull request associada... intenta posar enllaços interns amb `#NUMERO`.

**Comment by stefanlonn** [comment]
Es la PR #155! Ahora actualizo mis otros PR.
