### ISSUE TITLE
ReceiveDamage / Attack logic

### ISSUE THREAD

**Issue by JoanBenito** [NestorTejero/ES2016B#116]
Redefine how weapons attack and units and building receive damage
It works as follows:
- Tower and Unit detect the targets in their range and pass them on to their Weapon (in charge of attacking the targets in the queue via a Projectile it shoots).
- Building and Unit receive damage from a Projectile and if their health reaches 0, the game ends or they destroy themselves, respectively.

**Comment by kkaren** [comment]
To do:
- Refactor attacking/receiving damage code in concordance to the updated Class Diagram
- Test the new perfomance
- Make sure that what worked before still works

Definition of done:
- Refactor done following the new Class Diagram
- Unit and Tower attack correctly (correct collisions and Weapon assignments)
- Unit and Building receive damage (decrease health) correctly
- Units move correctly

Problems fixed:
- Units collide without going through the Building obejct or moving it

Estimated time on issue --> 8h
Real time on issue --> 3h + 2h + 4h + 1h = 10h
