### ISSUE TITLE
Create map v2

### ISSUE THREAD

**Issue by JoanBenito** [NestorTejero/ES2016B#118]

**Comment by iubeda** [comment]
- Mapa mas grande.
- Caminos/carreteras simulando el Eixample.
- Texturas para el terreno de fondo (cesped).
- Texturas para los caminos.

Tiempo estimado: 8h
Tiempo real: 3h+2h+1h+2h+2h = 10h

Definition of done:
- Terreno mas grande.
- Caminos y carreteras creados siguiendo una disposición similar al Eixample de Barcelona.
- Integrado en el proyecto y compilando.

**Comment by iubeda** [comment]
Closed in #144
