### ISSUE TITLE
Exchange student - 6h

### ISSUE THREAD

**Issue by vfernaco** [NestorTejero/ES2016B#123]
## Definitions of done:
1. Design of damage. (See character properly damaged)
2. Scaling, adapted size of models with scene.
3. Animations of walk,
   - Have to move correctly arms.
   - Have to move correctly legs.
4. Animations of attack 
   1. If character is melee:
      - Moving gun according to the arm.
   2. If character is rank:
      - Animation has to see like character is throwing an object.
5. Animation of die.
   - Have to stay on the ground before falling.
6. Integrated correctly in unity.

**Comment by jesusleon1995** [comment]
All done

**Comment by vcampoma7** [comment]
Se ha revisado las animaciones de atacar, caminar y morir de los diferentes personajes.
Hemos revisado las armas para entender la integración de los sonidos relacionados.
Todo correcto.

**Comment by NestorTejero** [comment]
@jesusleon1995 referent a #172 fixa't que pots reobrir una issue aquí a baix "reopen issue". Edito: veig que vas crear un nou issue perquè la pull request ja s'havia acceptat.
