### ISSUE TITLE
Crear menú d'administració de tropes

### ISSUE THREAD

**Issue by JMeyerr** [NestorTejero/ES2016B#14]

**Comment by Solero93** [comment]
Esto de dónde lo habéis sacado? xD

**Comment by quimix93** [comment]
De que cuando cliques una torre o unidad, se tiene que ver la ventana conforme si quieres hacer upgrade o que.

**Comment by Solero93** [comment]
Aaaaaaaaa vale! esto es lo que dijimos que estará en el HUD al final, como en el Age Of Empires por ejemplo.

Joe, es que el nombre confunde jajaja
