### ISSUE TITLE
Versió Unity 5.4.1f1

### ISSUE THREAD

**Issue by quimix93** [NestorTejero/ES2016B#16]
No sé quina versió fa servir la gent però la darrera és la 5.4.1f1 que diría va sortir fa com a molt un parell de setmanes i segurament és la que tenim tots els que hem descarregat el Unity en la darrera setmana per a fer el lliurament 0. El boilerplate penjat està en versió 5.3.x i en obrir-se amb versions posteriors, et fa actualitzar el projecte. Ho dic més que res per a que tothom que faci servir Unity es posi a la mateixa versió o comprobi quina té perquè podría haver cacao amb tema versions. (Un cop posats d'acord i tots tenint la mateixa, no actualitzar fins que el projecte estigui acabat).

**Comment by Solero93** [comment]
El boilerplate está a 5.3, perqué és el que hi ha als ordinadors de la uni xd si voleu que el faci en 5.4 per si de cas, no em costa res, ho puc parlar amb el profe, perqué ni dev ni master no s'han modificat encara

**Comment by quimix93** [comment]
Ho deia més que res perquè el tutorial del BounceBall demanava que s'actualitzesin els scripts perquè els que ja venien estaven obsolets. Però potser és el mateix tutorial que van donar l'any passat i està fet amb Unity 4 o a saber.

**Comment by Solero93** [comment]
Aquest tipus de problemes no haurien d'haver-hi, perquè el projecte base que tenim és de Unity 5 com hauria de ser.
