### ISSUE TITLE
Add values to HUD

### ISSUE THREAD

**Issue by ifernapa10** [NestorTejero/ES2016B#180]
The task will be finalize when completed the next points:
           -Add values of TIME, MONEY, WAVE, DIFICULTY, POINTS.
           -Hide the button of upgrade when the selected object isn't upgradeble.
           -Add values of  the selected object. (Attack speed).

Duration: 4h

**Comment by Solero93** [comment]
Tell me what info you need to show on the HUD. I'll do the appropiate getters

**Comment by ifernapa10** [comment]
@Solero93 We need the next getters:

-Time
-Money
-Wave
-Dificulty
-Points

From object selected:
Attack speed
Upgrade Button Functionality

**Comment by Solero93** [comment]
@niko227 Try to make all getters inside GameController since it should control all inputs-outputs of the Model

**Comment by stefanlonn** [comment]
Code review: Trabajo bien hecho y codigo claro.
