### ISSUE TITLE
Sound Integration

### ISSUE THREAD

**Issue by ire925** [NestorTejero/ES2016B#183]
The task will be finalize when completed the next points:
-Menu music sounds across multiple scenes
-Upload button, death, buy and weapon sound effects.
-Integrate all these effects in each object.
-To have a centralized point to administrate audio volumes (AudioMixer)

Duration: 8h

**Comment by jesusleon1995** [comment]
Se ha revisado la integración de los diferentes sonidos para los personajes del juego, así como también se ha revisado la implementación de la gestión del sonido.
