### ISSUE TITLE
Redo Grid

### ISSUE THREAD

**Issue by ire925** [NestorTejero/ES2016B#186]
The task will be finalize when completed the next points:
-
The user can toggle on/off the grid.
The user only can build a tower inside the grid if a valid position is choosen.
The grid moves along with the camera.

Duration: 8h

**Comment by iubeda** [comment]
The grid to build tower applies all over the terrain.
The grid don't validate the valid positions (right now).
The grid moves along with the camera.

**Comment by NestorTejero** [comment]
entenc que el que va comentar en @iubeda _the grid doesn't validate the valid positions_ es va corregir?
