### ISSUE TITLE
Search how to import animations and show them in Unity

### ISSUE THREAD

**Issue by jesusleon1995** [NestorTejero/ES2016B#193]
1.	Learn how to import animations in Unity after export a blender model with animations
2.	Learn how to show imported animations in Unity

**Comment by jdomenmi7** [comment]
The guide is in the [wiki](https://github.com/NestorTejero/ES2016B/wiki/Guide-to-add-animations-to-a-model-%28Prefab%29)

**Comment by sashadgt** [comment]
Code review done ,all good
