### ISSUE TITLE
Redesign current map

### ISSUE THREAD

**Issue by iubeda** [NestorTejero/ES2016B#198]
**To do:**
- Starting position on (0,0,0).
- Resize the current map.
- Placing buildings and other elements in the map.

**Definition of done:**
- The map has to be smaller.
- The map has to have buildings and other elements.
- Integrated

Estimated time: 6h

**Comment by quimix93** [comment]
Because of the lack of building models, we talked about the possibility of adding by the moment some 3d objects like cubes. Other aspects seem correct yet.

**Comment by iubeda** [comment]
For now the map is rescaled and positioned correctly. 
I am creating new buildings to add to the map (#231).

Time spent: 1.5h

**Comment by iubeda** [comment]
Time spent: 2h

**Comment by iubeda** [comment]
Finally this issue is closed in #254 . The design of the map will keep improving on next sprint.
