### ISSUE TITLE
Spawn AI doesn't work on Building Project after restart

### ISSUE THREAD

**Issue by Solero93** [NestorTejero/ES2016B#203]
### Context ###

- When running on Unity, the AI Spawns the Units and they start moving as expected

- However, when you build the project to show it as a whole, the AI spawns Unit on the first run, but if you restart the game anyhow, they don't spawn anymore.

### Definition of Done ###

- AI Spawns Unit even after restarting game on Project Build

**Comment by niko227** [comment]
Fixed, closed.
