### ISSUE TITLE
Fix attack 

### ISSUE THREAD

**Issue by kkaren** [NestorTejero/ES2016B#208]
#207 
## **Problem**

- The fact that the same target could be attacked by diferent weapons at the same time is not contemplated, therefore, if a target is killed by one weapon and the others try to attack that target, an error comes up and the scene collapses.

## **Definition of Done**

- When a Weapon calls Attack, it should go through the list of targets and get the first one available to shoot (removing the ones that have already been killed, independently of the weapon that did it) or none if the list is empty.

Estimated time: 1h

**Comment by kkaren** [comment]
Real time: 1h + 1h 30min = 2h 30min

**Comment by NestorTejero** [comment]
PR: #207
