### ISSUE TITLE
Combine all textures from characters into one

### ISSUE THREAD

**Issue by jdomenmi7** [NestorTejero/ES2016B#216]
Each character should have a single texture to facilitate the work of programmers later.
For example:
Angry Student Model: angryStudentTexture.png

Definition of done:
- All characters have a maximum of two textures (if character has one object it can has two textures, if not just one texture is allowed)
- Organize all character folders in a correct way
- Delete all unused files and folders

**Comment by niko227** [comment]
Code review: All perfect!
very good and useful job.
