### ISSUE TITLE
Unit attack sound

### ISSUE THREAD

**Issue by Solero93** [NestorTejero/ES2016B#219]
Unit sound attack plays even when they aren't attacking.

@kkaren investigated a bit and came to the conclusion: 

> The problem is not on the code, it's on the prefab. The sound is set to play on Awake.

**Comment by Solero93** [comment]
@sashadgt I've assigned this to you because you're also fixing the Unit Prefabs, so you've gotta take this into account.

**Comment by Solero93** [comment]
Included inside issue #237

**Comment by Solero93** [comment]
This is fixed already, right? If that's so, close this issue @sashadgt

**Comment by NestorTejero** [comment]
closed?

**Comment by Solero93** [comment]
Yup.
