### ISSUE TITLE
Define medium and hard AI

### ISSUE THREAD

**Issue by JoanBenito** [NestorTejero/ES2016B#233]
- Define a Medium AI, copy of easy with more enemies.
- Define a Hard AI wih knapsack problem algorism (greedy for the moment)

Definition of done:
- Medium AI available and working
- Hard AI available and working

Estimated time: 10h

Comments:
- Para hacer funcionar la Hard AI, hay que añadirle al prefab de unidad un coste (está actualmente a 0)
- Habría que pactar valores de algunos atributos (dinero inicial de la AI, coste de las unidades, etc..)

**Comment by stefanlonn** [comment]
Buen trabajo, los niveles tienen una diferencia de dificultad marcada. Hard habria que optimizarlo.

**Comment by NestorTejero** [comment]
PR: #147 #252 #162
