### ISSUE TITLE
Create Prefabs of Units

### ISSUE THREAD

**Issue by sashadgt** [NestorTejero/ES2016B#237]
- Create Prefabs for units,with working animations,correct unit sizes, and scripts

Definition of Done: Prefabs Execute animations correctly and have correct sizes, and linket to scripts

**Comment by Solero93** [comment]
#219 Take this into account

**Comment by sashadgt** [comment]
Created prefabs for this issue and made this pr #259 
Then when pr #260 were merged integrated it into project on pr #261 with help from others
Also there are 5 paced manualy on the map for testing aniamtions and prefabs pourposes only

**Comment by jdomenmi7** [comment]
Code Review. All good. Hay que quitar el audio source de algunos personajes. Buen treabajo!
