### ISSUE TITLE
Unify main menu with A.I.

### ISSUE THREAD

**Issue by niko227** [NestorTejero/ES2016B#255]
Definition of Done:
- crear los prefabs de MediumAI y HardAI.
- leer la dificultad desde el menú y instanciar el prefab correspondiente

estimated time: 3h

**Comment by niko227** [comment]
Done:
prefabs de MediumAI y HardAI creados.
leer la dificultad desde el menú y instanciar el prefab correspondiente

Para que funcione bien hay que cargar los prefabs de las IA en camera.

time total: 5h (hasta que no he encontrado que los prefabs de AI se tenian que cargar en camera he dado muchas vueltas)

**Comment by jesusleon1995** [comment]
Code review:
Todo perfecto, he entendido que ha unificado las ias ya que al principio únicamente estaba la fácil y, al parecer, tenía una complejidad elevada.

Muy buen trabajo!
