### ISSUE TITLE
Modify Camera

### ISSUE THREAD

**Issue by quimix93** [NestorTejero/ES2016B#265]
hours: 3h
Conditions of done:
-Being able to Zoom in/out
-Changing the way to move the camera (getting the mouse close to screen limits).

**Comment by iubeda** [comment]
Code review:
- The way to move the camera seems to work ok.
- Zoom not implemented yet.

**Comment by JMeyerr** [comment]
Code Review:
El "Zoom in/out" funciona correctamente, de manera eficient, i sense errors, tot i que més que zoom in/out és "up/down", varía únicament la posició Y de la càmara.
El moviment relatiu al pla de la càmera ja no consisteix a "clickar i arrastrar", sinó que funciona al portar el punter cap als extrems (amb una certa antelació) de la finestra. Permet moviment en 8 direccions, i funciona de manera correcte, eficient, i de nou, sense errors.
