### ISSUE TITLE
Improve Options(Main Menu)

### ISSUE THREAD

**Issue by quimix93** [NestorTejero/ES2016B#270]
- Improve "look&feel"
- Resize icons and size of text
- Add explication of each option

Time: 2.5h

**Comment by ifernapa10** [comment]
Se ha modificado el menú para que se adapte correctamente a varias resoluciones, y se ha implementado un nuevo diseño, buen trabajo!

**Comment by ghost** [comment]
Code review:

The options got an explanation and seems better distributed but it could be made a little more "pixel perfect" and I have doubts about the position of speaker icon

**Comment by ghost** [comment]
#300
