### ISSUE TITLE
Unit selection indicator

### ISSUE THREAD

**Issue by quimix93** [NestorTejero/ES2016B#272]
-Add a visual effect that makes feedback of what is selected in the game.
-Control if this means to change info of the HUD and changing it if it has to.

The task will end when:
-The task ends when a selector appears on the selected object

Estimated time: 4h

**Comment by ire925** [comment]
- When you select an object, you can display an indicator above it to see that it is selected
- Once a building / unit is selected, the states of this particular object are shown in the HUD

**Comment by ifernapa10** [comment]
Done.
