### ISSUE TITLE
2 Iconic buildings from Barcelona

### ISSUE THREAD

**Issue by stefanlonn** [NestorTejero/ES2016B#277]
Definition of done:
- Both buildings must have an aceptable number of polygons (not too high).
- Both need to be iconic (Torre Agbar, Sagrada Familia, etc..)

**Comment by jdomenmi7** [comment]
I'm doing MACBA ([edifici Meier](https://ca.wikipedia.org/wiki/Museu_d'Art_Contemporani_de_Barcelona#Edifici_Meier) and T[orre Agbar](https://ca.wikipedia.org/wiki/Torre_Agbar) . I close these issue and create a new one for each building.
