### ISSUE TITLE
Crumble animation for UB building

### ISSUE THREAD

**Issue by stefanlonn** [NestorTejero/ES2016B#280]
Definition of done:
- The animation should show the building crumbling or breaking.
- Animation is in an alternate model with same outside shape as the other ub building.

**Comment by JoanBenito** [comment]
Aun en estado muy prematuro pero vas por buen camino, espero que acabe igual que tus demás issues, osea de diez.

Buen trabajo.

**Comment by vcampoma7** [comment]
Se ha revisado la animación de explosión y la composición del objeto universidad destruido, que está compuesto por muchas piezas pequeñas para dar el efecto de explosión.
Falta combinarlo con la animación de explosión pero se está realizado un muy buen trabajo.

**Comment by pauortega** [comment]
collapsing animation is in the video #295  , no need to upload a model and animation for that
