### ISSUE TITLE
Advanced Map design

### ISSUE THREAD

**Issue by sashadgt** [NestorTejero/ES2016B#285]
**To do:**
- Place buildings and other elements on the map.
- Design map has to avoid placing many towers together.
- Add colliders to the buildings.

**Definition of done:**
- The map has to have buildings and other elements.
- Buildings with colliders.
- Integrated

Estimated time: 5h

**Comment by iubeda** [comment]
Related with #304 and #319. The PR is #326.

Time spent until now: 5.5h

**Comment by iubeda** [comment]
Closed in #326
