### ISSUE TITLE
Create ranking system

### ISSUE THREAD

**Issue by sashadgt** [NestorTejero/ES2016B#287]
As a User I want to have a score while I play and have a list of highscores to be able to beat myself.

DEFINITION OF DONE:

- A score is shown while you play

- After each game the final score is stored

- You have all the scores in a list (will be limited to 10)

**Comment by Solero93** [comment]
DONE, except storing the score, since there's no frontend to support it.

I wanted to talk to TeamC before storing since they'll be the ones who'll have to get the info for the High Score screen
