### ISSUE TITLE
Make towers have different ranges at each level

### ISSUE THREAD

**Issue by sashadgt** [NestorTejero/ES2016B#290]
Towers have multiplier of range 2.0 at each Upgrade
Definition of done, when leveling up tower its range doubles so it can shoot at more distance

**Comment by Solero93** [comment]
The range is multiplied by *1.2 at each level, what do we want exactly here?

**Comment by sashadgt** [comment]
#335 Solved here

**Comment by sashadgt** [comment]
Time:
Estimated 1 h / Real 1h
