### ISSUE TITLE
Make stats for Units, Towers, UB

### ISSUE THREAD

**Issue by sashadgt** [NestorTejero/ES2016B#292]
Make stats for units
Make stats for towers
Make stats for UB

**Comment by niko227** [comment]
Definition of done:

Modify the stats of Prefabs:

Angry student
Freshman student
Exchange student
Manifestant
Professor
Janitor

ajustar velocidad, daño de los enemigos, las torres y la UB para buscar la mejor jugabilidad.
Estimated time: 5h

**Comment by niko227** [comment]
Done: 
valores ajustados de los enemigos, dinero, torres, todo descrito en la siguiente tabla,
issue junto a #293
(La tabla en rojo es como estaba al principio, verde los datos actualizados)
![costs](https://cloud.githubusercontent.com/assets/11501575/21187993/285388d2-c21a-11e6-89c4-5846f10773ba.JPG)

Time: 10h (entre las 2 issues)

la issue no esta finalizada del todo, queda acabar de pulir la medium y la hard AI, hay varios factores a mirar antes de poder avanzar en el balanceo de toda la IA (como el correcto funcionamiento de las torres, bugs de que se acumulan...), me ha sido costoso avanzar e ir probando.

**Comment by niko227** [comment]
Definition of Done para el sprint 5: 
acabar de balancear los estados de las unidades y hacer que funcione correctamente

estimated time: 4h

**Comment by niko227** [comment]
Done:
valores equilibrados de las unidades, torres, ub, conjuntamente con la IA y el balanceo de su dinero

real time: 7h

**Comment by NestorTejero** [comment]
closed?
