### ISSUE TITLE
Balance AI and shop creating units

### ISSUE THREAD

**Issue by sashadgt** [NestorTejero/ES2016B#293]

**Comment by niko227** [comment]
Definition of done:

Ajustar y balancear los distintos tipos de IA, para buscar la jugabilidad adecuada,
controlar el flujo de creación de unidades y el numero de unidades por oleada.

Estimated time: 3h

**Comment by niko227** [comment]
Issue relacionada con #292 (he escrito ahí el estado de la issue)

**Comment by NestorTejero** [comment]
closed?

**Comment by NestorTejero** [comment]
gràcies, @niko227 !
