### ISSUE TITLE
Improve & create some buildings

### ISSUE THREAD

**Issue by iubeda** [NestorTejero/ES2016B#304]
**To do:**
- Create some buildings to integrate in the map.
- Improve the current buildings.

**Definition of done:**
- Buildings with materials & textures.
- Number of polygons should be as low as posible without losing the general aspect of the model.

Estimated time: 3h

**Comment by iubeda** [comment]
-Improved the current buildings.
- Created new one.

Time spent: 2h

The content of this issue is related with #285 and will pushed with it.

**Comment by iubeda** [comment]
Merge and other stuff... Finally the content of this issue will pushed separated of #285 

time spent: 1.5h

**Comment by quimix93** [comment]
We talked about the redistribution and everything seems correct.

**Comment by quimix93** [comment]
I can only see the top-left corner buildings in there. Is this possible?

**Comment by iubeda** [comment]
Closed in #319
