### ISSUE TITLE
Fix Unity Cloud Build

### ISSUE THREAD

**Issue by Solero93** [NestorTejero/ES2016B#320]
Unity Cloud builds right now don't show the models on the scene.

DEFINITION OF DONE:

- Cloud Build executable should look the same as Build & Run from Unity

**Comment by Solero93** [comment]
Took some hours investigating, seems that Asset Bundles need to be done. Or we have to pass all .blend to .fbx (at this point of the project that's an horror to ask)

To make Asset Bundles however, some scripting would be needed. I'll ask @NestorTejero whether I should fix it.

**Comment by NestorTejero** [comment]
How long can it take, @Solero93 ? Probably not worth investing too much time, but at the same time it can be useful to find a canonical way to do this and share with others.

**Comment by Solero93** [comment]
This won't be done, so I'm closing it.
