### ISSUE TITLE
Click Logic 2h

### ISSUE THREAD

**Issue by Solero93** [NestorTejero/ES2016B#34]
In GameController class create the logic of clicks:
- When clicked on the building, building's options should appear
- When clicking on unit, its life should appear
- When clicking outside of everything it gets deselected

**Comment by sashadgt** [comment]
Make Mouse raytracing work, when selecting objects

**Comment by sashadgt** [comment]
DONE

**Comment by Solero93** [comment]
Nope. Review PR

**Comment by sashadgt** [comment]
DONE 2.0
