### ISSUE TITLE
Highlight ability in map

### ISSUE THREAD

**Issue by niko227** [NestorTejero/ES2016B#357]
Make the ability to see where enemies of the wave appear more visible.

Estimated time: 1h

**Comment by JoanBenito** [comment]
Definition of done:
- Ahora en vez de usar un Halo en el component de los respawn point, es una spotlight con gran intensidad con la que se consigue un mejor resultado.
- Esta spotlight además dibuja un Halo, con lo que aún es más visible.
- El color en vez de ser rojo, cómo las unidades enemigas, es verde y así evitar confusiones.

Real time: 2h
