### ISSUE TITLE
Balance Hard AI

### ISSUE THREAD

**Issue by niko227** [NestorTejero/ES2016B#358]
Makes playable the Hard AI difficulty

Estimated time: 3h

**Comment by JoanBenito** [comment]
Definition of done:

- Ahora la función que calcula las unidades más rentables (más daño por menos coste) tiene en cuenta la vida de las unidades, para poder dar salida a las unidades "tanke".
- Para controlar excesos de unidades, ahora la mochila (Hard AI) tiene un límite de 6 unidades por iteración.
- Pequeño sistema de aborrecimiento de la unidad, cuando se añade en la mochila (Hard AI) varias veces la misma unidad se obliga a pasar a la siguiente más rentable.
- El dinero por segundo que gana la AI ha pasadode 5 a 3, con lo que conseguimos un mejor balanceo.
- Medium AI corregido para que no trate de comprar sin dinero suficiente.

Real time: 3h
