### ISSUE TITLE
Create Dummy Stuff for Scripting

### ISSUE THREAD

**Issue by Solero93** [NestorTejero/ES2016B#40]
- Create some dummy cubes as models to try our scripts
- Create some dummy scenes to the same.

**Comment by iubeda** [comment]
Creado un edificio y una torre/persona para poder asociar los eventos temporalmente.

**Comment by Solero93** [comment]
@iubeda  gracias! todos abrid las ramas desde aquí

**Comment by Solero93** [comment]
Ahora sí... escena creada con objetos chorra. Los árboles son los enemigos y los cilindros las torres

**Comment by Solero93** [comment]
it's in folder DummyGame
