### ISSUE TITLE
HUD Structure (4h)

### ISSUE THREAD

**Issue by JMeyerr** [NestorTejero/ES2016B#8]
Make a HUD that adapts to the game

Time estimated: 4h

--- Requirements ---
1. It must be connected with values of the game, at least partialy
2. It must have the next layout:
![image](https://cloud.githubusercontent.com/assets/11064187/20162109/17aa46a2-a6f3-11e6-95a5-38ea9d4d5046.png)
3. The smallest height segment must mesure 216px

**Comment by Solero93** [comment]
If you could do it for the Dummy Scene also, it would be awesome :smile:

**Comment by Solero93** [comment]
Don't close the issue until it's on dev
